In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print("hello Numpy")

hello Numpy


In [4]:
a=34

In [5]:
b=13.5

In [6]:
c=a+b

In [7]:
c

47.5

In [8]:
print("Good Luck")

Good Luck


### Numpy
* Numerical Python : Majorily works with array called nd array
* 
n darray: n dimensional arra y* 
It is one of the statistical library comes with many statistical functions and package* s
it is one of the open source library which is built in c compil* er
Numpy is the fast processed library built with C compi* ler
Every numpy array is already compiled with C so that it will take less time to exec* ute.
Why numpy is developed where python already has list data structure.

In [9]:
ls=[1,2,3,4,5,6,7,8]
ls

[1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
ls[4]

5

In [11]:
arr=np.array([1,2,3,4,5,6,7,8])

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr[4]

5

In [14]:
ls2=[[1,2,3],[4,5,6],[7,8,9]]
ls2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2     #matrix 3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2.ndim   #ndim :number of dimension

2

In [17]:
ls*2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
arr*2  #in multiplication form 

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [19]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [20]:
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

In [21]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2.shape   #shape shows no.of rows and columns

(3, 3)

In [23]:
arr2.size   #size return number of element in array

9

In [24]:
arr3=np.arange(5,67,8)
arr3

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [25]:
np.arange(20)  #stop

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
arr4=np.arange(1,65)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [28]:
arr4.ndim

1

In [29]:
arr4.shape

(64,)

In [30]:
arr4.size

64

In [31]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [32]:
b=4,5,6,7,8
type(b)

tuple

In [33]:
c= 45,

In [34]:
type(c)

tuple

In [35]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [36]:
arr4.reshape(2,32)   #reshape used to change dimensional of array, while doing it we cannot change size of an array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [37]:
arr4.reshape(4,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [38]:
arr4.reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [39]:
arr4.reshape(16,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [40]:
arr4.reshape(32,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42],
       [43, 44],
       [45, 46],
       [47, 48],
       [49, 50],
       [51, 52],
       [53, 54],
       [55, 56],
       [57, 58],
       [59, 60],
       [61, 62],
       [63, 64]])

In [41]:
arr4.reshape(64,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])

In [42]:
arr4.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])