In [1]:
import numpy as np

In [2]:
def info_array(a):
    print("Dimension -", a.ndim)
    print("shape-",a.shape)
    print("size(number of elements)-",a.size)
    print("Datatype-",a.dtype)

In [3]:
arr1=np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Operations in Array

In [4]:
arr1.ndim

1

In [5]:
arr1.shape

(12,)

In [6]:
arr1.size

12

In [7]:
info_array(arr1)

Dimension - 1
shape- (12,)
size(number of elements)- 12
Datatype- int32


### Numpy Notes
* arange- To create range of element - syntax: np.arange(start,end,step)
* Linspace- To create the range of element with number of element.This will calculate step size by its own, it will also include the start and end value. syntax: np.linspace(start,end, number_of_element)
* Reshape- change the shape of array syntax: np.reshape (row,column), while reshaping array the size of array should not change.

### Linspace

In [8]:
arr2=np.linspace(1,2,34)
arr2

array([1.        , 1.03030303, 1.06060606, 1.09090909, 1.12121212,
       1.15151515, 1.18181818, 1.21212121, 1.24242424, 1.27272727,
       1.3030303 , 1.33333333, 1.36363636, 1.39393939, 1.42424242,
       1.45454545, 1.48484848, 1.51515152, 1.54545455, 1.57575758,
       1.60606061, 1.63636364, 1.66666667, 1.6969697 , 1.72727273,
       1.75757576, 1.78787879, 1.81818182, 1.84848485, 1.87878788,
       1.90909091, 1.93939394, 1.96969697, 2.        ])

In [9]:
arr3=np.linspace(10,45,6)
arr3

array([10., 17., 24., 31., 38., 45.])

In [10]:
arr4=np.linspace(1,9,4)
arr4

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [11]:
arr5=np.linspace(1,5,125)
arr5

array([1.        , 1.03225806, 1.06451613, 1.09677419, 1.12903226,
       1.16129032, 1.19354839, 1.22580645, 1.25806452, 1.29032258,
       1.32258065, 1.35483871, 1.38709677, 1.41935484, 1.4516129 ,
       1.48387097, 1.51612903, 1.5483871 , 1.58064516, 1.61290323,
       1.64516129, 1.67741935, 1.70967742, 1.74193548, 1.77419355,
       1.80645161, 1.83870968, 1.87096774, 1.90322581, 1.93548387,
       1.96774194, 2.        , 2.03225806, 2.06451613, 2.09677419,
       2.12903226, 2.16129032, 2.19354839, 2.22580645, 2.25806452,
       2.29032258, 2.32258065, 2.35483871, 2.38709677, 2.41935484,
       2.4516129 , 2.48387097, 2.51612903, 2.5483871 , 2.58064516,
       2.61290323, 2.64516129, 2.67741935, 2.70967742, 2.74193548,
       2.77419355, 2.80645161, 2.83870968, 2.87096774, 2.90322581,
       2.93548387, 2.96774194, 3.        , 3.03225806, 3.06451613,
       3.09677419, 3.12903226, 3.16129032, 3.19354839, 3.22580645,
       3.25806452, 3.29032258, 3.32258065, 3.35483871, 3.38709

In [12]:
info_array(arr5)

Dimension - 1
shape- (125,)
size(number of elements)- 125
Datatype- float64


### Reshape

In [13]:
arr6=np.linspace(1,24,24,dtype="int")
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
arr6.shape

(24,)

In [15]:
arr6.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [16]:
arr6.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [17]:
arr6.reshape(12,2)   #assignment 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [18]:
arr6.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [19]:
arr6.reshape(8,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [20]:
arr6.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [21]:
arr6.reshape(3,4,2)    # layesr=3,columns=4,rows=2   #3d array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [22]:
np.shape(arr6.reshape(3,4,2))

(3, 4, 2)

In [23]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
arr6=arr6.reshape(6,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [25]:
arr6.reshape(24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [26]:
arr6.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [27]:
arr6.reshape(1,-1)  #it is in 2d form 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [28]:
arr6.reshape(1,-1).shape

(1, 24)

In [29]:
arr6.reshape(24).shape

(24,)

In [30]:
arr6.ravel("C") #c programming 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [31]:
arr6.ravel("F")   #element pick as column wise  #Fortron : one of the programming language 

array([ 1,  5,  9, 13, 17, 21,  2,  6, 10, 14, 18, 22,  3,  7, 11, 15, 19,
       23,  4,  8, 12, 16, 20, 24])

### Resize

In [32]:
arr6.resize(8,3)   #it is change in memory ..operation done in memory

In [33]:
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [34]:
arr6.resize(3,8)
arr6

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr6.resize(7,5) #not possible

ValueError: cannot resize this array: it does not own its data

In [36]:
np.resize(arr6,(7,5))  #possible

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24,  1],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [37]:
np.resize(arr6,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr7=np.arange(4,16).reshape(3,4)
arr7

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.resize(arr7,(5,4))

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Concatenate

In [40]:
arr8=np.arange(1,7).reshape(2,3)
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr9=np.arange(7,13).reshape(2,3)
arr9

array([[ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.concatenate([arr8,arr9])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
np.concatenate([arr8,arr9],axis=1)   #after axis it is join row wise 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [44]:
np.concatenate([arr8,arr9], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
arr10=np.arange(13,19).reshape(3,2)
arr10

array([[13, 14],
       [15, 16],
       [17, 18]])

In [46]:
np.concatenate([arr8,arr10])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

### H Stack

In [47]:
np.hstack([arr8,arr9])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### V Stack

In [48]:
np.vstack([arr8,arr9])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Repeat

In [49]:
arr11=np.arange(3)
arr11

array([0, 1, 2])

In [50]:
arr11.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [51]:
arr11.repeat(23)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2])

In [52]:
arr11.repeat([3,5,6])

array([0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

### Idenity Matrix
* syntax:np.eye()used to create identity matrix,where diagonal element became 1 and rest of the element will be 0


In [53]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.eye(3,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [55]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [56]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.eye(3,7,4)    #for changing diagonal element 

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [58]:
np.ones((3,4))   # for ones matrix    enter only shape 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.zeros((3,6))   # for zeros matrix   

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### Split

In [ ]:
* split function is used the numpy array into multiple arrays

In [61]:
arr6

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
np.split(arr6,(1,2))

[array([[1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24]])]

In [63]:
arr12=np.linspace(1,100,100,dtype="int").reshape(10,10)
arr12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [64]:
np.split(arr12,[3,6])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [65]:
np.split(arr12,[3])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [66]:
np.split(arr12,[2,4,6,8])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]),
 array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]]),
 array([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [ ]:
sp1,sp2,sp3=np.split(arr12,[2,4,6,8],axis=1)

In [67]:
np.split(arr12,[4,7],axis=1)

[array([[ 1,  2,  3,  4],
        [11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34],
        [41, 42, 43, 44],
        [51, 52, 53, 54],
        [61, 62, 63, 64],
        [71, 72, 73, 74],
        [81, 82, 83, 84],
        [91, 92, 93, 94]]),
 array([[ 5,  6,  7],
        [15, 16, 17],
        [25, 26, 27],
        [35, 36, 37],
        [45, 46, 47],
        [55, 56, 57],
        [65, 66, 67],
        [75, 76, 77],
        [85, 86, 87],
        [95, 96, 97]]),
 array([[  8,   9,  10],
        [ 18,  19,  20],
        [ 28,  29,  30],
        [ 38,  39,  40],
        [ 48,  49,  50],
        [ 58,  59,  60],
        [ 68,  69,  70],
        [ 78,  79,  80],
        [ 88,  89,  90],
        [ 98,  99, 100]])]